### ISSUE TITLE
Version 1.4.0 Downloads files with wrong permissions

### ISSUE THREAD

**Issue by MegaShinySnivy** [SpottedSqueak/FA-Gallery-Downloader#12]
See the title, on Linux the files downloaded in downloaded_content have the wrong permissions set. downloaded_content has no read, write, or execute permissions, and so nothing can be downloaded unless it is manually changed afterward. Same with the subfolders and subfiles.

**Comment by ItsAlphaNeon** [comment]
Can confirm, was just about to create an issue.

**Comment by MegaShinySnivy** [comment]
Exact permissions are ---/---/r--

**Comment by ItsAlphaNeon** [comment]
This occurs with older builds as well, I'm seeing.

**Comment by elseways** [comment]
This problem happens in macOS too.

**Comment by SpottedSqueak** [comment]
Oh, interesting! I had folks on both operating systems try it out and this was never mentioned. I'll recheck the permissions on this.

**Comment by SpottedSqueak** [comment]
Just pushed a new update, lemme know if that addresses the issues here!

**Comment by MegaShinySnivy** [comment]
Seems to work! Thank you!
