### ISSUE TITLE
Importing data doesn't work + feature request

### ISSUE THREAD

**Issue by Mark-B97** [SpottedSqueak/FA-Gallery-Downloader#13]
After updating to 2.0.4 I tried clicking "import data" as instructed but it won't detect the old files, but it shows I'm still logged in and when I click to view gallery everything is already there and working as intended, so idk if it's a bug or intended behaviour. I'm using it in arch linux.

Also I don't know how feasible this is but it would be nice if we could have a list of usernames we can add and remove entries from, so we could potentially just press "update" or something similar to have it download stuff that has been added since last time we finished downloading. This could also work as a queue if we add multiple usernames to the list so we can leave it downloading overnight for example

**Comment by SpottedSqueak** [comment]
I'm confused. You click "Import data", and you can view the gallery and everything is still there? And you're logged in? So what's missing?

**Comment by SpottedSqueak** [comment]
Also if you have the username box empty and click "Continue previous download" it'll resume all current downloads.

**Comment by Mark-B97** [comment]
Well, wasn't it supposed to be empty after the update and then when we click on "import data" it would pick up the files from the previous version? As it sits now it seems it's doing that automatically (or at least it did for me), so why do we need to click and import data?

**Comment by SpottedSqueak** [comment]
Depending on how folks extract the zip contents, it could end up a folder or two deep. I was trying to account for that! That's why it asks if you're missing data on the startup menu. I should have clarified that, depending on the OS, that step might not have been needed, sorry!
