### ISSUE TITLE
Feature Request: Batched Username Downloading

### ISSUE THREAD

**Issue by ItsAlphaNeon** [SpottedSqueak/FA-Gallery-Downloader#14]
Currently, the application supports downloading galleries on a user-by-user basis, which, while functional, limits efficiency in handling larger or multiple gallery downloads. The process requires manual initiation of each download following the completion of the previous one, making it less convenient for users who wish to download galleries from multiple users in one session. Given the impossibility of running multiple instances of the application, a feature allowing batch downloads would save a lot of time for certain users that wish to archive multiple galleries.

**Comment by SpottedSqueak** [comment]
I've thought about implementing this... How does a comma-delimited list sound?

**Comment by ItsAlphaNeon** [comment]
That sounds perfect, and shouldn't need any UI changes, just under the hood method reworks. Thanks for considering this!

**Comment by SpottedSqueak** [comment]
Added that in in the latest release!
