### ISSUE TITLE
Downloading error spammed and unable to download anything else.

### ISSUE THREAD

**Issue by RandomFluffyUser** [SpottedSqueak/FA-Gallery-Downloader#15]
hiya, hope this is the right spot to put this. But essentially there is this small issue i don't know how to fix. I did initially start with the 1.4 version but decided to delete all traces of it and install the newer version so im not sure if that caused the issue. But I have been archiving a few galleries and after one the downloads don't work anymore? The command window spams a "File not found" error with the same file listed multiple times, i tried deleting that users whole gallery from the folder, i tried making that file and putting it in both the thumbnail's and main user gallery folder and nothing has seemed to work. It even spams it when trying to download other user's galleries? And I have no idea why.
If you need a full picture of the output i can provide it but i don't think the rest of the picture is necessary, just the start.
![Screenshot 2024-08-08 220630](https://github.com/user-attachments/assets/7d6bdd15-4355-4022-8914-3f59025916f4)
I can also try providing any other issues if necessary.
Also to be clear I have enough space on my drive, and I have gotten a small chunk of other galleries before this so I know the tool in fact works (which I wanted to put out there thanks for developing this!!)

**Comment by SpottedSqueak** [comment]
Actually yeah, what's the full thumbnail name? Thing is, FA sometimes deletes thumbnails and the URL just goes nowhere. If I have an example I could likely make a fix for it.

**Comment by RandomFluffyUser** [comment]
![Screenshot 2024-08-08 223041](https://github.com/user-attachments/assets/985a2e9f-dcf5-40d9-9c92-486477410204)
Here you go! Seriously not sure what was wrong with this one and why its preventing me from downloading any new galleries. I can provide whatever other info you need as well.

**Comment by SpottedSqueak** [comment]
Okay, yeah, that submission has a broken image. Lemme see about changing how the program handles that.

**Comment by SpottedSqueak** [comment]
That's addressed in the latest build!

**Comment by RandomFluffyUser** [comment]
Alright thank you! That seems to have fixed the issue and I can download galleries again, and thanks again for developing this tool!!
