### ISSUE TITLE
No way to cancel an aborted download?

### ISSUE THREAD

**Issue by mira-drgn** [SpottedSqueak/FA-Gallery-Downloader#16]
Is there any way to clear out any pending downloads? I went to download a user's gallery and favorites, only to find that totaled 75k submissions. So I canceled the download, figuring I'd uncheck favorites and try again. But now every time I initiate a download from _any_ user, I still get the message "[Data] Saving data for 75434 submissions..." in the log. It seems like now that the program has stored the metadata of those submissions, it's determined to download all of them no matter what. Is there any fix or workaround for this, or a button or setting I haven't located?

**Comment by SpottedSqueak** [comment]
Hmm. As a temporary workaround (and if you don't have any other galleries downloaded) you can delete the "fa_gallery_downloader" folder. I'll try to come up with a feature for this in the meantime!

**Comment by SpottedSqueak** [comment]
Addressed in the latest build!
