### ISSUE TITLE
Cannot Export to Postybirb, Username Has Underscore(?)

### ISSUE THREAD

**Issue by starringer** [SpottedSqueak/FA-Gallery-Downloader#2]
My username has an underscore in it. (star_ringer)
However, my actual URL does not have one. (starringer)

1. I log in as "star_ringer".
> The app shows "starringer" on the app account list.
>> My default browser is Firefox, but it opens the login in Chrome?

2. I click "Download User Gallery".
> "Requested downloads complete! ♥"

3. I click "View Gallery". 
> All my submissions are downloaded and displayed under "C:/Users/****/AppData/Local/Temp/caxa/applications/fa-gallery-downloader-v1.0.8/xk6pqk0vxi/0/html/gallery.html".
>> The "by" on all the items is "star_ringer".

4. I click "Export: Postybirb"
> "[Data] No submissions to export: starringer"

5. I change the "Gallery to download" field to "star_ringer" and click "Export: Postybirb"
> "[Data] No submissions to export: starringer"

**Comment by SpottedSqueak** [comment]
Oh wow, I didn't realize this was an issue actually! For now I'm taking a look into it and will fix this as soon as I can! Thanks for bringing it up!

**Comment by SpottedSqueak** [comment]
Also I'll note that Firefox isn't on Chromium, so it doesn't work with the app unfortunately! I did attempt to work with it at one point, but it was a huge mess trying to get it to run properly, so I dropped support for it.

**Comment by SpottedSqueak** [comment]
Should be fixed in latest release: https://github.com/SpottedSqueak/FA-Gallery-Downloader/releases/tag/v1.0.9

If you could confirm I'll close the issue!

**Comment by starringer** [comment]
That worked! However, there's a new issue:

> [log] [Data] Exporting 420 submissions for account: starringer
[error] [Error: ENOENT: no such file or directory, lstat '***\fa_gallery_downloader\downloaded_content\starringer\1147541569.starringer_gargoyle.jpg'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '***\\fa_gallery_downloader\\downloaded_content\\starringer\\1147541569.starringer_gargoyle.jpg'
}
[log] [Error] Data export failed, check logs

I checked my directory, and it has the folder as "downloaded_content\star_ringer", not "downloaded_content\starringer". I can work around this by changing the directory name, and it works fine otherwise.

**Comment by SpottedSqueak** [comment]
Ah, of course XD Okay, I'll make a fix for that too! Knew I missed something, lol.

**Comment by SpottedSqueak** [comment]
Okay, got a fix for that in with the latest release! Since it was already manually fixed on your end, I'll mark this as closed unless someone finds another issue like this; feel free to open another issue if anyone does!
