### ISSUE TITLE
Cant download anything from Furaffinity! How to fix?

### ISSUE THREAD

**Issue by vlad8599** [SpottedSqueak/FA-Gallery-Downloader#21]
It seems that I have some problems with downloader after long using it. First of all, here is a error at start.
![image](https://github.com/user-attachments/assets/03a579c3-aed8-4fb8-a8a9-d70721a33c27)

Any ideas?

**Comment by SpottedSqueak** [comment]
Well, Furaffinity is currently down! You won't be able to download anything from there till it's back up. 

If there's another error, I don't see it here, that's just a deprecation warning! What exactly is the problem you're having?

**Comment by SpottedSqueak** [comment]
Are things working okay now that the site is back up?

**Comment by vlad8599** [comment]
yeah, its working again just fine, thank you
