### ISSUE TITLE
Program crashes while downloading

### ISSUE THREAD

**Issue by Nomaxice** [SpottedSqueak/FA-Gallery-Downloader#3]
My boyfriend and I have been encountering a consistent issue with the program under Windows crashing a bit after starting a gallery download, sometimes it won't even restart after a crash until restarting the system entirely, even logging out and back in the session isn't enough.

This happened with multiple various galleries, no underscore in usernames. Restarting shows it's not a specific file crashing as it manages to download them when retrying without issue.

This has happened through multiple versions of the program so far, too, but seems to be less prone to happen on 1.0.4 from my testing, and pretty much assured to happen on later versions.

A couple logs of the latest crashes included.
Devices affected are a windows 10 and a windows 11 machine, using local drives on both for downloads.

Let me know if you need anything else that could help!

[debug-1689082455770.log](https://github.com/SpottedSqueak/FA-Gallery-Downloader/files/12015641/debug-1689082455770.log)
[debug-1689083494780.log](https://github.com/SpottedSqueak/FA-Gallery-Downloader/files/12015642/debug-1689083494780.log)

**Comment by SpottedSqueak** [comment]
This sounds like a permission issue from the logs... Try running the program as admin? I'll dig into it more, but this is something I've not been able to replicate, hmm.

**Comment by SpottedSqueak** [comment]
Okay, latest release *should* address this. Let me know if it works for you: https://github.com/SpottedSqueak/FA-Gallery-Downloader/releases/tag/v1.0.11

**Comment by Nomaxice** [comment]
Was gonna say admin didn't change anything, I'll give the new version a go and get back to you !

**Comment by Nomaxice** [comment]
Alas, still getting the issue, latest log attached
[debug-1689100901896.log](https://github.com/SpottedSqueak/FA-Gallery-Downloader/files/12018058/debug-1689100901896.log)

**Comment by SpottedSqueak** [comment]
Do you mind getting in contact me outside of here? DM me here or on FA and I can work with you directly to figure this out!

**Comment by Nomaxice** [comment]
Sure, I got the same username pretty much everywhere if you want to send a poke on the communication source of your choice, heading to sleep here, so I'll check back tomorrow!

**Comment by SpottedSqueak** [comment]
Sent a note on FA! I made a change last night but no clue if it'll fix things or not for you. We can talk more one-on-one and figure this out!

**Comment by Nomaxice** [comment]
Saw it!

**Comment by SpottedSqueak** [comment]
Resolved with latest release v1.0.14
