### ISSUE TITLE
Program stops without reporting anything specific uppon "file not found"

### ISSUE THREAD

**Issue by Nomaxice** [SpottedSqueak/FA-Gallery-Downloader#4]
Stumbled on a new issue, starting a gallery download, it seems to begin and reports in the GUI 'starting downloads...", however after a bit, the stop button greys out and nothing else happens in the status, progress bars are empty, and logs show it met a file not found. Unsure if it completed the other file downloads, or if it abandoned at the missing file and gave up before getting the rest of the gallery.
It also appears to try getting the file from the earlier gallery attempted, even after specifically entering another gallery?
Log shows file from previous gallery in the list despite being set to archive beherit.

Sorry for more issues, I seem to be real good at finding bugs in software >.>

edit: Also seems that if trying to start a new download despite the program clearly not doing anything, and log showing no more activity other than file not found, it will throw a "program already running", and then clicking stop and trying again, it will start downloading from the next gallery, until it hits the same issue again.

[debug-1689333963636.log](https://github.com/SpottedSqueak/FA-Gallery-Downloader/files/12049926/debug-1689333963636.log)

**Comment by SpottedSqueak** [comment]
Well, the downloads are done in the order they were added to the database! So it wouldn't start with the current user if there are unfinished downloads from a previous gallery; it would want to finish those older ones first. I'll take a look though.

**Comment by SpottedSqueak** [comment]
Addressed in latest release v1.1.0. Lemme know if it works for you! Thanks!
