### ISSUE TITLE
Occasional crash on start

### ISSUE THREAD

**Issue by Nomaxice** [SpottedSqueak/FA-Gallery-Downloader#5]
Pardon the absolute jank screenshot, but as the CMD window closes instantly after hitting the error, this is the best I could time to see the error with a makeshift unicolor background.
For some reason, after a fresh boot, going back to the program game me a missing module error.
I think that is the issue I occasionally had when the program wouldn't start randomly, issue is it's random so, hard to really pin down a particular cause.

It doesn't seem to resolve itself after logging out and back in, or even after a reboot, though, even redownloading the file, including to a different drive, does not seem to fix it.
Also of note, while all the versions are in the same folder, they are not all affected, only the one is hitting the issue.
I'm rather confused at what happened that just causes this problem 
so if you have any insights, I would gladly welcome them.

![image](https://github.com/SpottedSqueak/FA-Gallery-Downloader/assets/10945524/eb472c25-d5c6-4a74-baa0-dd5da0231df0)

**Comment by Nomaxice** [comment]
Follow up, I've attemped something dirty, aka, since it's complaining it's not finding the index.js in the temp folder in appdata but the older version found it... I just copied over the previous version's to the new folder and it worked.
I suppose, from what I understand, there needs to be a check if it's missing and get the files back if they're somehow missing, given it's a temp folder it had to grab them to begin with so it seems it just assumes they'll still be there when it got them in the past, and get confused that windows might have cleared the temp folder during a reboot without actually removing everything?

Edit: Entirely removing the [random string] folder also fixes it without making the program think it's the older version as it unpacks back properly. So yeah definitely it's just getting confused that the folder exists but misses the files windows cleared up on reboot with its dubious temp clearing efficacy leaving bits and pieces around... Thanks windows I guess?

**Comment by SpottedSqueak** [comment]
If this is an issue, might need to just delete the entire Caxa folder in temp and reinstall! I wonder if this is an issue that occurs when there's been so many revisions, like you said it might be something weird with Windows and the temp folder! I don't think I can fix this. My program relies on installing to temp to run, and if the files don't install properly in the temp folder I can't run any code to fix that! This may just be a known issue that I can't resolve.

**Comment by Nomaxice** [comment]
A bit late, I apologize for that, but, yeah, seems to just be that it would perhaps need to re-install if the js is missing on start, but, I am not familiar enough to know how hard/possible that would be, as it does re-install proper when manually clearing the folder entirely, but understandable if it's not fix-able
