### ISSUE TITLE
Rare issue with loading data

### ISSUE THREAD

**Issue by Shikellamy** [SpottedSqueak/FA-Gallery-Downloader#6]
It seems if someone were to delete their page while it waits in queue to be loaded it will cause the program to get stuck in an infinite loop of attempting to load in any of their submissions for download.

**Comment by Shikellamy** [comment]
I managed to create my own little janky fix by simply adding in the link ID, URL and marking the submission as saved. Idk if this is a bug even worth fixing as the odds of it occurring are so slim!

**Comment by SpottedSqueak** [comment]
That's... Certainly an edge case, yeah. XD So, if they delete it before anything is downloaded? Or while in the middle of downloading something? I should put a check in place for that though!

**Comment by Shikellamy** [comment]
I think it occurred because I had queued up my favorites to download, and while still in the process of collecting the data a person deleted their account, which caused an infinite loop of trying to download the submission info.

**Comment by SpottedSqueak** [comment]
Aha, gotcha...Lemme see what I can do about that. I can add a check to make sure things exist in that case.

**Comment by SpottedSqueak** [comment]
Okay, my latest release should address this!
