### ISSUE TITLE
Feature Request? 

### ISSUE THREAD

**Issue by githubuserthatisstupid** [SpottedSqueak/FA-Gallery-Downloader#7]
Hi would like a featured to download deleted accounts/arts is that possible?

**Comment by SpottedSqueak** [comment]
That is not actually possible, sorry! For that sort of thing, you'll wanna look at a project like this: https://furarchiver.net/

It archives most every account that's been on FA, so it has all of that past info; my program can only gather what's already currently there. It doesn't keep a history of past/deleted accounts.
