### ISSUE TITLE
Error with the downloaded folder name.

### ISSUE THREAD

**Issue by FErDaiif** [SpottedSqueak/FA-Gallery-Downloader#9]
Some accounts have used symbols that are not supported by the file system, which causes issues with incorrect file names when downloading folders. I hope to add a feature for symbol replacement.

![屏幕截图 2024-06-16 210318](https://github.com/SpottedSqueak/FA-Gallery-Downloader/assets/58466481/3df17cd3-7bbb-460c-b1d8-8ec2270c742a)

**Comment by FErDaiif** [comment]
username shoegaze.
down folder should be named shoegaze.
Under the NTFS file system, folders cannot end with a period as it will cause the folder to be inaccessible.
The folder created when accessing remotely via SMB is named SNFSP4~F.

**Comment by SpottedSqueak** [comment]
Interesting...Hmm. I'll look into this when I get some time! If you had a PR for it I'd be happy to take a look though. I'll also look into what symbols are not acceptable and work on escaping them properly.

**Comment by SpottedSqueak** [comment]
Should be addressed in the latest release here: https://github.com/SpottedSqueak/FA-Gallery-Downloader/releases/tag/v1.4.0
